version: '3'
services:
  node-app:
    image: registry:${BUILD_NUMBER}
    ports:
      - "3000:3000"
    networks:
      - my-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - my-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app

networks:
  my-network:

